package de.lukegoll.application.xmlEntities.constants;

public enum DocumentType {

    NONE, MAIN_DOCUMENT,
    CORRESPONDENCE, REPAIR_COST_ASSUMPTION,
    DECLARATION_OF_ASSIGNMENT, INVOICE, DELIVERY_RECEIPT, DUNNING,
    ADDITIONAL_DOCUMENT, IMAGE, PRELIMINARY_CALCULATION,
    FOREIGN_INVOICE, DATA_PROTECTION, CLAIM_IMAGE, ACCIDENT_DOCUMENT,
    RENTAL_CAR_OFFERS, CALCULATION, CALCULATION_PROTOCOL, VALUATION,
    VALUATION_PROTOCOL, VIN_PROTOCOL, REDUCED_MARKET_VALUE;


}
